### ISSUE TITLE
MechDriver not running.

### ISSUE THREAD

**Issue by PrayShah** [Auto-Mech/mechdriver#431]
Hi. I installed the whole AutoMech suite from conda via the following command "conda env create auto-mech/amech-env", by downloading the amech-full.yml file. I was able to successfully install and activate the AutoMech Environment. However, if I try to tun MechDriver as per AutoMech documentation it gives the following error:

![Screenshot 2023-03-14 112653](https://user-images.githubusercontent.com/112137720/225088283-4045b46b-3352-4fa6-adf5-189417b7440d.png)

It executes the "mess" command perfectly but not the "mdriver". 

I downloaded the "automech.py" script from the GitHub page and try to run it in amech-env as well. I got the following error.

![image](https://user-images.githubusercontent.com/112137720/225089253-277045ac-9560-4dfd-81c8-c816eb3ba592.png)

I am not sure why it's not able to find routines as I downloaded AutoMech from conda. 

Am I making any installation mistakes? Am I supposed to perform a few more installation steps after the conda installation? Could you please help me resolve this issue?

**Comment by avcopan** [comment]
Hi @PrayShah -- what you're doing looks like it should work, at a glance. One of the developers will do some testing and get back to you.

**Comment by PrayShah** [comment]
Hi @avcopan. Thank you for looking into it. Looking forward to your response.

**Comment by avcopan** [comment]
This is resolved by the new installation procedure. The code can be installed with a simple conda install as described [here](https://github.com/Auto-Mech#install), but currently it is preferable to install from source by following [these instructions](https://github.com/Auto-Mech/amech-dev?tab=readme-ov-file#automech-developer-set-up) as we are actively debugging to arrive at a release.
